### ISSUE TITLE
Show better error message when parsing Cargo.toml failed

### ISSUE THREAD

**Issue by bobogei81123** [PyO3/setuptools-rust#32] opened 2018-04-16 04:58 UTC
I was confounded by the error message `error: rust build failed; unable to find any *'...'.so in ...`. It turned out that I used single quote instead of double quote when quoting a string.
For example, changing the Cargo.toml in example/ to
```
[lib]
crate-type = ["cdylib"]
name = 'helloworld'
```
cause this confusing error.

**Comment by althonos** [comment] 2018-04-16 09:33
@bobogei81123 : actually, the real issue here is that single quotes were not handled properly. `setuptools-rust` would then expect the built library to be named `lib'helloworld'.so` instead of `libhelloworld.so` (since quotes were not escaped), and so the error message is actually right :smile:

I'll push a fix for single quotes to be handled as intended.

**Comment by althonos** [comment] 2018-04-18 23:05
Fix is now in *master* and will be included in next version. If you need a new release shortly, you can tag **fafhrd91** in this issue :wink:

**Closed by althonos** 2018-04-18 23:05 UTC
