### ISSUE TITLE
1.1.1: pytest and tox are failing

### ISSUE THREAD

**Issue by kloczek** [PyO3/setuptools-rust#201] opened 2021-12-04 20:02 UTC
I'm trying to package your module as an rpm package. So I'm using the typical build, install and test cycle used on building packages from non-root account.
- "setup.py build"
- "setup.py install --root </install/prefix>"
- "pytest with PYTHONPATH pointing to sitearch and sitelib inside </install/prefix>

looks like pytest is not able to find any units and tox is failing:
<deftails>

pytest
```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-setuptools-rust-1.1.1-2.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-setuptools-rust-1.1.1-2.fc35.x86_64/usr/lib/python3.8/site-packages
+ /usr/bin/pytest -ra setuptools_rust
=========================================================================== test session starts ============================================================================
platform linux -- Python 3.8.12, pytest-6.2.5, py-1.10.0, pluggy-0.13.1
benchmark: 3.4.1 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
Using --randomly-seed=3474840361
rootdir: /home/tkloczko/rpmbuild/BUILD/setuptools-rust-1.1.1
plugins: shutil-1.7.0, virtualenv-1.7.0, mock-3.6.1, cov-2.12.1, anyio-3.3.4, forked-1.3.0, xdist-2.3.0, flaky-3.7.0, tornasync-0.6.0.post2, console-scripts-1.2.0, trio-0.7.0, timeout-2.0.1, asyncio-0.16.0, freezegun-0.4.2, flake8-1.0.7, pyfakefs-4.5.3, hypothesis-6.29.3, benchmark-3.4.1, profiling-1.7.0, datadir-1.3.1, regressions-2.2.0, randomly-3.8.0
collected 0 items

========================================================================== no tests ran in 0.07s ===========================================================================
```
tox:
```console
+ SETUPTOOLS_SCM_PRETEND_VERSION=1.1.1
+ /usr/bin/tox --skip-missing-interpreters
GLOB sdist-make: /home/tkloczko/rpmbuild/BUILD/setuptools-rust-1.1.1/setup.py
mypy create: /home/tkloczko/rpmbuild/BUILD/setuptools-rust-1.1.1/.tox/mypy
ERROR: invocation failed (exit code 1), logfile: /home/tkloczko/rpmbuild/BUILD/setuptools-rust-1.1.1/.tox/mypy/log/mypy-0.log
================================================================================ log start =================================================================================
RuntimeError: failed to build image wheel because:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/virtualenv/seed/embed/via_app_data/via_app_data.py", line 51, in _install
    key = Path(installer_class.__name__) / wheel.path.stem
AttributeError: 'NoneType' object has no attribute 'path'


================================================================================= log end ==================================================================================
ERROR: InvocationError for command /usr/bin/python3 -m virtualenv --no-download --python /usr/bin/python3 mypy (exited with code 1)
pytest create: /home/tkloczko/rpmbuild/BUILD/setuptools-rust-1.1.1/.tox/pytest
ERROR: invocation failed (exit code 1), logfile: /home/tkloczko/rpmbuild/BUILD/setuptools-rust-1.1.1/.tox/pytest/log/pytest-0.log
================================================================================ log start =================================================================================
RuntimeError: failed to build image wheel because:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/virtualenv/seed/embed/via_app_data/via_app_data.py", line 51, in _install
    key = Path(installer_class.__name__) / wheel.path.stem
AttributeError: 'NoneType' object has no attribute 'path'


================================================================================= log end ==================================================================================
ERROR: InvocationError for command /usr/bin/python3 -m virtualenv --no-download --python /usr/bin/python3 pytest (exited with code 1)
_________________________________________________________________________________ summary __________________________________________________________________________________
ERROR:   mypy: InvocationError for command /usr/bin/python3 -m virtualenv --no-download --python /usr/bin/python3 mypy (exited with code 1)
ERROR:   pytest: InvocationError for command /usr/bin/python3 -m virtualenv --no-download --python /usr/bin/python3 pytest (exited with code 1)
```
<deftails>

**Comment by davidhewitt** [comment] 2021-12-16 00:01
For `pytest`, we only have doctests at the moment. You might want to look at our github-actions file to see how we test each of the examples (using tox).

As for the tox error, I'm afraid I have no idea. That looks like an upstream bug rather than something directly caused by this library.

**Comment by kloczek** [comment] 2021-12-16 00:14
On packaging anything test suite execution is IMO crucial.
In my own set of almost 800 python modules packages using such methodology I was able to expose many issues not only in tested modules but in other modules involved in test suite execution (if you will check my profile you would be able find hundreds of issue tickets becoming kind of shrapnels in last year :)).
So please be aware that general goal of the such thing like test suite execution is not sensu stricte about testing just packaged module :)
From that point of view .. more tests units always is  better :P

**Comment by davidhewitt** [comment] 2021-12-16 00:25
Yes, I fully agree. It takes time to write tests, and most the functionality we have in this package is integration tested in CI.

When I can split logic into small functions I've been adding doctests as a quick way to add some testing infrastructure. Now that I have the pytest CI job I'd be tempted to add more unit tests when I get the chance.

**Comment by kloczek** [comment] 2021-12-28 23:10
OK I've added --doctest-modules to pytest args and now I have in my build procedure the same level of thesting which is in tox.
However I think that default option should be listed in pytest.ini.

**Comment by davidhewitt** [comment] 2022-01-01 22:43
Sure thing, I'll add a pytest.ini in the next release. How do you acquire sources for packaging? From the GitHub release tarball?

**Comment by kloczek** [comment] 2022-01-01 23:17
I'm using tar ball from git tag.

**Comment by davidhewitt** [comment] 2022-04-26 17:51
I think this should have been resolved by addition of a `pyproject.toml` in `setuptools-rust` 1.2.0. Please ping if still having issues.

**Closed by davidhewitt** 2022-04-26 17:51 UTC
