### ISSUE TITLE
Investigate options for automatic installation of setuptools_rust

### ISSUE THREAD

**Issue by ssokolow** [PyO3/setuptools-rust#2] opened 2017-04-01 17:06 UTC
Currently, anything built using this requires a manual `pip install setuptools-rust` before its `setup.py` can be run.

I've never encountered any other `setup.py`-based solution where `pip install whatever` may fail for lack of a dependency that *can* be `pip install`ed, but requires a separate command. An attempt should be made to find a workaround for that.

**Comment by fafhrd91** [comment] 2017-04-01 17:16
yes, I agree. i will check what can be done.

**Comment by naufraghi** [comment] 2017-04-03 10:57
[pbr - Python Build Reasonableness](https://docs.openstack.org/developer/pbr/#setup-py) does this, but does not requires any special import, reading the real configuration from `setup.cfg`:

```python
#!/usr/bin/env python

from setuptools import setup

setup(
    setup_requires=['pbr>=1.9', 'setuptools>=17.1'],
    pbr=True,
)
```

Allowing to pass a tuple in `rust_extensions` and instantiating the `RustExtension` later, one could achieve this:

```python
from setuptools import setup

setup(name='hello-rust',
      version='1.0',
      setup_requires=['setuptools-rust>=x.y', 'setuptools>=17.1'],  # to better investigate
      rust_extensions=[('hello_rust._helloworld', 'extensions/Cargo.toml')],
      packages=['hello_rust'],
      # rust extensions are not zip safe, just like C-extensions.
      zip_safe=False
)
```

**Comment by ssokolow** [comment] 2017-04-04 05:32
I don't see a problem with that.

It'd even have the benefit that you could make it backwards-compatible with existing `setup.py` uses with a simple `isinstance` check.

**Comment by fafhrd91** [comment] 2017-04-04 05:34
yes, that is good idea. I will try to made this change during next couple days

**Comment by naufraghi** [comment] 2017-04-04 08:37
The only problem I see in the simple solution I proposed, is that we cannot pass a named argument within the `tuple`.

Other options for `rust_extensions` may be:

```python
rust_extensions=[dict(name='hello_rust._helloworld',
                      path='extensions/Cargo.toml',
                      debug=False)]
```
But we are forced to use the names for positional arguments too. To solve this, we can use an `(args, kwargs)` tuple:
```python
rust_extensions=[(('hello_rust._helloworld', 'extensions/Cargo.toml'),  # args
                  {"debug": False})]  # kwargs
```
or, with a little helper:
```python
ext = lambda *args, **kwargs: (args, kwargs)
rust_extensions=[ext('hello_rust._helloworld', 'extensions/Cargo.toml', debug=False)]
```

Other options?

**Comment by ssokolow** [comment] 2017-04-04 10:03
I'd drop into #python on FreeNode  and ask for opinions. Despite being quite experienced with Python, I'm still a novice when it comes to knowing The Right Way™ to design an API like this compared to some of the guys who hang out there.

**Comment by ofek** [comment] 2017-04-08 12:58
+1

**Comment by fafhrd91** [comment] 2017-05-02 14:51
here is another idea:

```python
try:
    from setuptools_rust import RustExtension
except ImportError:
    import subprocess
    import sys
    errno = subprocess.call([sys.executable, '-m', 'pip', 'install', 'setuptools-rust'])
    if errno:
        print("Please install setuptools-rust package")
        raise SystemExit(errno)
    else:
        from setuptools_rust import RustExtension

```

**Comment by ssokolow** [comment] 2017-05-08 13:22
The main problem I see with that last one is that it feels like an ugly hack (mostly but not entirely because of how it uses the `subprocess` module) and seeing an "ugly hack" as a recommended solution risks making potential users worry about two things:

1. Are there any undiscovered caveats lurking in it?
2. If the bit I can see is such an ugly hack? How ugly, hacky, and potentially unreliable is the rest?

**Comment by fafhrd91** [comment] 2017-05-08 15:25
Sure, it is hack. But whole setuptools-rust package is hack.

**Comment by ssokolow** [comment] 2017-05-08 15:49
Whether or not that's true, I'd take an `args`/`kwargs` tuple over `subprocess` any day.

Using `subprocess` in the `setup.py` for projects which depend on `setuptools-rust` would run the risk of making me look less skilled than I am since setup-time dependencies are such an obvious "must have" for `setuptools` that people are likely to come to the wrong conclusion about why `subprocess` was chosen.

**Comment by ssokolow** [comment] 2017-05-08 15:49
Whether or not that's true, I'd take an `args`/`kwargs` tuple over `subprocess` any day.

Using `subprocess` in the `setup.py` for projects which depend on `setuptools-rust` would run the risk of making me look less skilled than I am since setup-time dependencies are such an obvious "must have" for `setuptools` that people are likely to come to the wrong conclusion about why `subprocess` was chosen.

**Comment by ssokolow** [comment] 2017-05-08 15:49
Whether or not that's true, I'd take an `args`/`kwargs` tuple over `subprocess` any day.

Using `subprocess` in the `setup.py` for projects which depend on `setuptools-rust` would run the risk of making me look less skilled than I am since setup-time dependencies are such an obvious "must have" for `setuptools` that people are likely to come to the wrong conclusion about why `subprocess` was chosen.

**Comment by fafhrd91** [comment] 2017-05-08 19:56
in any case this is just idea.

**Comment by ssokolow** [comment] 2017-09-21 05:09
While doing virtualenv deployment testing with [this idea](https://github.com/PyO3/setuptools-rust/issues/2#issuecomment-298658919), I discovered that it doesn't work because a `python setup.py` process started before `pip` refuses to recognize modules which are then installed by the `pip` subprocess it calls.

Here's how I worked around it:

```python
# Workaround from https://github.com/PyO3/setuptools-rust/issues/2
try:
    from setuptools_rust import Binding, RustExtension
except ImportError:
    import os, subprocess, sys
    try:
        subprocess.check_call([sys.executable, '-m', 'pip',
                               'install', 'setuptools-rust'])
        os.execvp(sys.executable, [sys.executable] + sys.argv)
    except subprocess.CalledProcessError as err:
        print("Please install setuptools-rust package")
        raise SystemExit(err.errno)
```

**Comment by Victor-Savu** [comment] 2018-06-09 17:27
Version 10 of `pip` now implements support for [PEP 518](https://www.python.org/dev/peps/pep-0518/) which has a solution for this problem. Simply add a file named `pyproject.toml` next to your `setup.py` with the following contents (adapted from the example in [PEP 518](https://www.python.org/dev/peps/pep-0518/#specification) to include `setuptools-rust`):
```toml
[build-system]
requires = ["setuptools", "setuptools-rust", "wheel"].
```

`pip` will pick this file up before looking at `setup.py`and will pull the build-system requirements (among which `setuptools-rust`)

**Comment by konstin** [comment] 2018-08-04 14:05
Just confirmed that `pyproject.toml` works when used with `pip install -e .`. Closing this since we can't get any better solution with setuptools.

**Closed by konstin** 2018-08-04 14:05 UTC

**Comment by fantix** [comment] 2021-03-31 05:00
Another workaround here (putting above fixes together):

1. Add `setuptools_rust` to `setup_requires` in `setup.py` (for `python setup.py` calls)
2. Add `setuptools_rust` to `build-system.requires` in `pyproject.toml` (for `pip install` calls)
3. Use a generator to avoid the import/install circle:

```python
def get_rust_extensions():
    import setuptools_rust
    yield setuptools_rust.RustExtension(...)

setup(
    ...
    rust_extensions=get_rust_extensions(),
)
```
